* 简介
*Dlog* 是一个简易的静态博客生成器，使用python编写，命令简单，没有传统静态博客生成器的复杂，需要填写时间/作者等一系列信息。但是定制性很高而定制门槛很低，由于首页被看作普通文章，所以您可以尽情编写您的主页。

* 安装
由于Dlog暂时没有二进制版本，所以请您使用Python3。
** 安装Python3
首先，请您安装Python3（下文假设您配置了环境变量）。
** 初始化
接下来，请您将此项目克隆到任意您想要的目录并且您可以重命名此文件夹，比如 =Blog=.

然后运行 =python -m pip install -r requirements.txt=
** 使用
接下来您就可以创建您的博客了！在 =posts= 文件夹中创建您的文章文件，并且创建 =index= 文件（例如： =index.md= ），在里面填写您希望展示在博客主页的内容（例如文章列表和自我介绍）。

dlog支持的文档格式广泛，支持所有pandoc可以导出为 =html= 的输入格式.

另外，您需要配置 =config.toml= 来设置基本信息，像这样:
#+begin_src toml
  siteName = "网站名称"
  siteTitle = "网站标题"
  theme = "主题"
  siteUrl = "网站将被部署到的地址，用于回到首页"

  noBuildFiles = ["在posts文件夹中","你想不进行转换的文件夹","将原样拷贝到生成结果中"]
#+end_src
目前本项目自带的主题有： =example= ，您也可以自己编写主题/使用别人编写的主题，具体详见“自定义”一节。

此时，您就配置好了一切！在项目根目录运行 =python3 main.py= 后，build文件夹中便是您的网站（几乎所有的静态托管网站均支持设置网站根目录，您可以去设置为 =build= ）！

* 自定义
如果您是高级用户，您可以对此项目进行自定义。

您可以修改 =main.py= ，那是生成器的所有代码，您可以修改它，以便它符合您的要求，为此，我们为您准备了非常详细的注释。

或者，您还可以自定义主题，在 =themes/主题名称/template/post.html= 中编写您的主题，这份主题将被应用于主页和文章（因为主页也是文章）。其中：
+ ={{{postBody}}}= 将被替换为文章html。
+ 除此之外， ={{{xxx}}}= 将被替换为 =config.toml= 中的xxx的值。
+ 以上两种在任意一行最多一共出现一次。


并且，主题文件夹中的所有其他文件都会原样拷贝到生成结果根目录以便您使用。

* 贡献
由于此项目刚刚问世，如果您发现了Bug🐛/希望新功能，真诚的希望您的能为我们提ISSUE/PR,感谢！
